name: Builds
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["apk --debug", "ios --no-codesign --debug", web]
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        with:
          channel: stable
      - run: flutter config --enable-macos-desktop
      - run: flutter doctor -v

      # Checkout repository code and get packages.
      - name: Checkout repository code
        uses: actions/checkout@v2
      - run: flutter pub get -v

      - name: pod install
        working-directory: ./ios
        run: pod install

      - run: flutter build ${{ matrix.target }}