# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter dart analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Flutter dart analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout and get packages.
      - name: Checkout repository code
        uses: actions/checkout@v3

      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter config --enable-linux-desktop

      - run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get -v

      - run: flutter pub run build_runner build

      - name: Analyze project source
        run: flutter analyze
